title: Jean-Marc MONTOUT
author: Jean-Marc MONTOUT
email: montout.jeanmarc@gmail.com
logo: assets/jean-marc.jpg
description: > # this means to ignore newlines until "baseurl:"
  Développeur Web
  
show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
