title: My first static website
author: Jean-Marc
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first great production!

theme: jekyll-theme-cayman
